/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Rahaaon API
 * Crowdsourced tracker of wasteful public spending (rahaaon.fi).
 * OpenAPI spec version: 0.1.0
 */

export type AmountType = typeof AmountType[keyof typeof AmountType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AmountType = {
  exact: 'exact',
  approx: 'approx',
  min: 'min',
  unknown: 'unknown',
} as const;
