/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Rahaaon API
 * Crowdsourced tracker of wasteful public spending (rahaaon.fi).
 * OpenAPI spec version: 0.1.0
 */
import type { ArchiveRefAnyOfArchiveStatus } from './archiveRefAnyOfArchiveStatus';

export type ArchiveRefAnyOf = {
  submissionId: string;
  archiveStatus: ArchiveRefAnyOfArchiveStatus;
  hasArchivedText: boolean;
};
