/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Rahaaon API
 * Crowdsourced tracker of wasteful public spending (rahaaon.fi).
 * OpenAPI spec version: 0.1.0
 */

export type Category = typeof Category[keyof typeof Category];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Category = {
  Rakentaminen: 'Rakentaminen',
  'IT-hankkeet': 'IT-hankkeet',
  Konsultit: 'Konsultit',
  Kulttuuri: 'Kulttuuri',
  Viestintä: 'Viestintä',
  Matkustus: 'Matkustus',
  Muu: 'Muu',
} as const;
