/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Rahaaon API
 * Crowdsourced tracker of wasteful public spending (rahaaon.fi).
 * OpenAPI spec version: 0.1.0
 */
import type { Category } from './category';

export interface GenerateKeywordsRequest {
  /**
   * @minLength 1
   * @maxLength 300
   */
  title: string;
  /**
   * @minLength 1
   * @maxLength 2000
   */
  summary: string;
  /** @maxLength 120 */
  entity: string;
  category: Category;
}
