/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Rahaaon API
 * Crowdsourced tracker of wasteful public spending (rahaaon.fi).
 * OpenAPI spec version: 0.1.0
 */

export * from './category';
export * from './errorResponse';
export * from './errorResponseError';
export * from './getApiMe200';
export * from './health';
export * from './healthStatus';
export * from './me';
export * from './meUser';
export * from './patchApiAdminItemsId200';
export * from './patchItem';
export * from './patchSuggestion';
export * from './postApiAdminSuggestionsIdApprove200';
export * from './postApiAdminSuggestionsIdReject200';
export * from './postApiSuggestions201';
export * from './readiness';
export * from './readinessDb';
export * from './readinessStatus';
export * from './suggestUrl';
export * from './suggestion';
export * from './suggestionPreview';
export * from './voteResult';
export * from './wasteItem';