/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Rahaaon API
 * Crowdsourced tracker of wasteful public spending (rahaaon.fi).
 * OpenAPI spec version: 0.1.0
 */
import type { AmountType } from './amountType';
import type { PatchSuggestionAmountMaxEur } from './patchSuggestionAmountMaxEur';
import type { Category } from './category';
import type { PatchSuggestionArticlePublishedAt } from './patchSuggestionArticlePublishedAt';

export interface PatchSuggestion {
  /**
   * @minLength 1
   * @maxLength 300
   */
  title?: string;
  /**
   * @minLength 1
   * @maxLength 2000
   */
  summary?: string;
  /** @maxLength 500 */
  quote?: string;
  /** @minimum 0 */
  amountEur?: number;
  amountType?: AmountType;
  /** @minimum 0 */
  amountMaxEur?: PatchSuggestionAmountMaxEur;
  /**
   * @minLength 1
   * @maxLength 120
   */
  entity?: string;
  category?: Category;
  articlePublishedAt?: PatchSuggestionArticlePublishedAt;
  /** @maxItems 10 */
  keywords?: string[];
}
