/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Rahaaon API
 * Crowdsourced tracker of wasteful public spending (rahaaon.fi).
 * OpenAPI spec version: 0.1.0
 */
import type { ReadinessStatus } from './readinessStatus';
import type { ReadinessDb } from './readinessDb';

export interface Readiness {
  status: ReadinessStatus;
  db: ReadinessDb;
}
