/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Rahaaon API
 * Crowdsourced tracker of wasteful public spending (rahaaon.fi).
 * OpenAPI spec version: 0.1.0
 */

export type ReadinessDb = typeof ReadinessDb[keyof typeof ReadinessDb];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ReadinessDb = {
  up: 'up',
  down: 'down',
} as const;
