/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Rahaaon API
 * Crowdsourced tracker of wasteful public spending (rahaaon.fi).
 * OpenAPI spec version: 0.1.0
 */

export type ReadinessStatus = typeof ReadinessStatus[keyof typeof ReadinessStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ReadinessStatus = {
  ok: 'ok',
  degraded: 'degraded',
} as const;
