/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Rahaaon API
 * Crowdsourced tracker of wasteful public spending (rahaaon.fi).
 * OpenAPI spec version: 0.1.0
 */
import type { AmountType } from './amountType';
import type { SuggestionAmountMaxEur } from './suggestionAmountMaxEur';
import type { Category } from './category';
import type { SuggestionArticlePublishedAt } from './suggestionArticlePublishedAt';

export interface Suggestion {
  id: string;
  url: string;
  title: string;
  amountEur: number;
  amountType: AmountType;
  amountMaxEur: SuggestionAmountMaxEur;
  entity: string;
  category: Category;
  sourceName: string;
  articlePublishedAt: SuggestionArticlePublishedAt;
  summary: string;
  aiNote: string;
  confidence: number;
  createdAt: string;
}
