/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Rahaaon API
 * Crowdsourced tracker of wasteful public spending (rahaaon.fi).
 * OpenAPI spec version: 0.1.0
 */
import type { Category } from './category';

export interface Suggestion {
  id: string;
  url: string;
  title: string;
  amountEur: number;
  entity: string;
  category: Category;
  sourceName: string;
  summary: string;
  aiNote: string;
  confidence: number;
  createdAt: string;
}
