/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Rahaaon API
 * Crowdsourced tracker of wasteful public spending (rahaaon.fi).
 * OpenAPI spec version: 0.1.0
 */
import type { Category } from './category';

export interface SuggestionPreview {
  title: string;
  amountEur: number;
  entity: string;
  category: Category;
  sourceName: string;
  summary: string;
  aiNote: string;
  /**
   * @minimum 0
   * @maximum 100
   */
  confidence: number;
}
