/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Rahaaon API
 * Crowdsourced tracker of wasteful public spending (rahaaon.fi).
 * OpenAPI spec version: 0.1.0
 */
import type { UrlSubmissionArchiveStatus } from './urlSubmissionArchiveStatus';
import type { UrlSubmissionProcessError } from './urlSubmissionProcessError';

export interface UrlSubmission {
  id: string;
  url: string;
  title: string;
  description: string;
  siteName: string;
  createdAt: string;
  archiveStatus: UrlSubmissionArchiveStatus;
  hasArchivedText: boolean;
  processing: boolean;
  processError: UrlSubmissionProcessError;
}
