/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Rahaaon API
 * Crowdsourced tracker of wasteful public spending (rahaaon.fi).
 * OpenAPI spec version: 0.1.0
 */

export type UrlSubmissionArchiveStatus = typeof UrlSubmissionArchiveStatus[keyof typeof UrlSubmissionArchiveStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UrlSubmissionArchiveStatus = {
  pending: 'pending',
  ok: 'ok',
  paywalled: 'paywalled',
  failed: 'failed',
  missing: 'missing',
  disabled: 'disabled',
} as const;
