/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Rahaaon API
 * Crowdsourced tracker of wasteful public spending (rahaaon.fi).
 * OpenAPI spec version: 0.1.0
 */
import type { Category } from './category';
import type { WasteItemArticlePublishedAt } from './wasteItemArticlePublishedAt';

export interface WasteItem {
  id: string;
  title: string;
  amountEur: number;
  entity: string;
  category: Category;
  sourceName: string;
  sourceUrl: string;
  summary: string;
  quote: string;
  hidden: boolean;
  publishedAt: string;
  articlePublishedAt: WasteItemArticlePublishedAt;
  votes: number;
  voted: boolean;
}
