/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Rahaaon API
 * Crowdsourced tracker of wasteful public spending (rahaaon.fi).
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ArchiveTextEdit,
  ErrorResponse,
  GetApiAdminSubmissionsIdArchiveTextParams,
  PatchApiAdminItemsId200,
  PatchItem,
  PatchSuggestion,
  PostApiAdminSubmissionsIdProcess200,
  PostApiAdminSubmissionsIdReject200,
  PostApiAdminSuggestionsIdApprove200,
  PostApiAdminSuggestionsIdReject200,
  PutApiAdminSubmissionsIdArchiveText200,
  RejectedSuggestion,
  RejectedUrlSubmission,
  Suggestion,
  UrlSubmission,
  WasteItem
} from '.././model';

import { apiFetch } from '../../lib/api-fetch';




/**
 * @summary All published items including hidden ones (editorial)
 */
export const getApiAdminItems = (
    
 signal?: AbortSignal
) => {
      
      
      return apiFetch<WasteItem[]>(
      {url: `/api/admin/items`, method: 'GET', ...(signal ? { signal }: {})
    },
      );
    }
  



export const getGetApiAdminItemsQueryKey = () => {
    return [
    `/api/admin/items`
    ] as const;
    }

    
export const getGetApiAdminItemsQueryOptions = <TData = Awaited<ReturnType<typeof getApiAdminItems>>, TError = ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminItems>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAdminItemsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAdminItems>>> = ({ signal }) => getApiAdminItems(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAdminItems>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAdminItemsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAdminItems>>>
export type GetApiAdminItemsQueryError = ErrorResponse


export function useGetApiAdminItems<TData = Awaited<ReturnType<typeof getApiAdminItems>>, TError = ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminItems>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAdminItems>>,
          TError,
          Awaited<ReturnType<typeof getApiAdminItems>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAdminItems<TData = Awaited<ReturnType<typeof getApiAdminItems>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminItems>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAdminItems>>,
          TError,
          Awaited<ReturnType<typeof getApiAdminItems>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAdminItems<TData = Awaited<ReturnType<typeof getApiAdminItems>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminItems>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary All published items including hidden ones (editorial)
 */

export function useGetApiAdminItems<TData = Awaited<ReturnType<typeof getApiAdminItems>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminItems>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAdminItemsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Hide an item from the feed, or restore it (editorial)
 */
export const patchApiAdminItemsId = (
    id: string,
    patchItem: PatchItem,
 ) => {
      
      
      return apiFetch<PatchApiAdminItemsId200>(
      {url: `/api/admin/items/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchItem
    },
      );
    }
  


export const getPatchApiAdminItemsIdMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiAdminItemsId>>, TError,{id: string;data: PatchItem}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof patchApiAdminItemsId>>, TError,{id: string;data: PatchItem}, TContext> => {

const mutationKey = ['patchApiAdminItemsId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiAdminItemsId>>, {id: string;data: PatchItem}> = (props) => {
          const {id,data} = props ?? {};

          return  patchApiAdminItemsId(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiAdminItemsIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiAdminItemsId>>>
    export type PatchApiAdminItemsIdMutationBody = PatchItem
    export type PatchApiAdminItemsIdMutationError = ErrorResponse

    /**
 * @summary Hide an item from the feed, or restore it (editorial)
 */
export const usePatchApiAdminItemsId = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiAdminItemsId>>, TError,{id: string;data: PatchItem}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiAdminItemsId>>,
        TError,
        {id: string;data: PatchItem},
        TContext
      > => {

      const mutationOptions = getPatchApiAdminItemsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary The AI queue: pending suggestions, newest first
 */
export const getApiAdminSuggestions = (
    
 signal?: AbortSignal
) => {
      
      
      return apiFetch<Suggestion[]>(
      {url: `/api/admin/suggestions`, method: 'GET', ...(signal ? { signal }: {})
    },
      );
    }
  



export const getGetApiAdminSuggestionsQueryKey = () => {
    return [
    `/api/admin/suggestions`
    ] as const;
    }

    
export const getGetApiAdminSuggestionsQueryOptions = <TData = Awaited<ReturnType<typeof getApiAdminSuggestions>>, TError = ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminSuggestions>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAdminSuggestionsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAdminSuggestions>>> = ({ signal }) => getApiAdminSuggestions(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAdminSuggestions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAdminSuggestionsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAdminSuggestions>>>
export type GetApiAdminSuggestionsQueryError = ErrorResponse


export function useGetApiAdminSuggestions<TData = Awaited<ReturnType<typeof getApiAdminSuggestions>>, TError = ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminSuggestions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAdminSuggestions>>,
          TError,
          Awaited<ReturnType<typeof getApiAdminSuggestions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAdminSuggestions<TData = Awaited<ReturnType<typeof getApiAdminSuggestions>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminSuggestions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAdminSuggestions>>,
          TError,
          Awaited<ReturnType<typeof getApiAdminSuggestions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAdminSuggestions<TData = Awaited<ReturnType<typeof getApiAdminSuggestions>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminSuggestions>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary The AI queue: pending suggestions, newest first
 */

export function useGetApiAdminSuggestions<TData = Awaited<ReturnType<typeof getApiAdminSuggestions>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminSuggestions>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAdminSuggestionsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Apply editorial edits to a pending suggestion
 */
export const patchApiAdminSuggestionsId = (
    id: string,
    patchSuggestion: PatchSuggestion,
 ) => {
      
      
      return apiFetch<Suggestion>(
      {url: `/api/admin/suggestions/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchSuggestion
    },
      );
    }
  


export const getPatchApiAdminSuggestionsIdMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiAdminSuggestionsId>>, TError,{id: string;data: PatchSuggestion}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof patchApiAdminSuggestionsId>>, TError,{id: string;data: PatchSuggestion}, TContext> => {

const mutationKey = ['patchApiAdminSuggestionsId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiAdminSuggestionsId>>, {id: string;data: PatchSuggestion}> = (props) => {
          const {id,data} = props ?? {};

          return  patchApiAdminSuggestionsId(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiAdminSuggestionsIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiAdminSuggestionsId>>>
    export type PatchApiAdminSuggestionsIdMutationBody = PatchSuggestion
    export type PatchApiAdminSuggestionsIdMutationError = ErrorResponse

    /**
 * @summary Apply editorial edits to a pending suggestion
 */
export const usePatchApiAdminSuggestionsId = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiAdminSuggestionsId>>, TError,{id: string;data: PatchSuggestion}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiAdminSuggestionsId>>,
        TError,
        {id: string;data: PatchSuggestion},
        TContext
      > => {

      const mutationOptions = getPatchApiAdminSuggestionsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Publish a pending suggestion to the feed
 */
export const postApiAdminSuggestionsIdApprove = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return apiFetch<PostApiAdminSuggestionsIdApprove200>(
      {url: `/api/admin/suggestions/${id}/approve`, method: 'POST', ...(signal ? { signal }: {})
    },
      );
    }
  


export const getPostApiAdminSuggestionsIdApproveMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAdminSuggestionsIdApprove>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiAdminSuggestionsIdApprove>>, TError,{id: string}, TContext> => {

const mutationKey = ['postApiAdminSuggestionsIdApprove'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAdminSuggestionsIdApprove>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  postApiAdminSuggestionsIdApprove(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiAdminSuggestionsIdApproveMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAdminSuggestionsIdApprove>>>
    
    export type PostApiAdminSuggestionsIdApproveMutationError = ErrorResponse

    /**
 * @summary Publish a pending suggestion to the feed
 */
export const usePostApiAdminSuggestionsIdApprove = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAdminSuggestionsIdApprove>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAdminSuggestionsIdApprove>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getPostApiAdminSuggestionsIdApproveMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Reject a pending suggestion
 */
export const postApiAdminSuggestionsIdReject = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return apiFetch<PostApiAdminSuggestionsIdReject200>(
      {url: `/api/admin/suggestions/${id}/reject`, method: 'POST', ...(signal ? { signal }: {})
    },
      );
    }
  


export const getPostApiAdminSuggestionsIdRejectMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAdminSuggestionsIdReject>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiAdminSuggestionsIdReject>>, TError,{id: string}, TContext> => {

const mutationKey = ['postApiAdminSuggestionsIdReject'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAdminSuggestionsIdReject>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  postApiAdminSuggestionsIdReject(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiAdminSuggestionsIdRejectMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAdminSuggestionsIdReject>>>
    
    export type PostApiAdminSuggestionsIdRejectMutationError = ErrorResponse

    /**
 * @summary Reject a pending suggestion
 */
export const usePostApiAdminSuggestionsIdReject = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAdminSuggestionsIdReject>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAdminSuggestionsIdReject>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getPostApiAdminSuggestionsIdRejectMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary The rejected archive: rejected suggestions, newest rejection first
 */
export const getApiAdminSuggestionsRejected = (
    
 signal?: AbortSignal
) => {
      
      
      return apiFetch<RejectedSuggestion[]>(
      {url: `/api/admin/suggestions/rejected`, method: 'GET', ...(signal ? { signal }: {})
    },
      );
    }
  



export const getGetApiAdminSuggestionsRejectedQueryKey = () => {
    return [
    `/api/admin/suggestions/rejected`
    ] as const;
    }

    
export const getGetApiAdminSuggestionsRejectedQueryOptions = <TData = Awaited<ReturnType<typeof getApiAdminSuggestionsRejected>>, TError = ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminSuggestionsRejected>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAdminSuggestionsRejectedQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAdminSuggestionsRejected>>> = ({ signal }) => getApiAdminSuggestionsRejected(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAdminSuggestionsRejected>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAdminSuggestionsRejectedQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAdminSuggestionsRejected>>>
export type GetApiAdminSuggestionsRejectedQueryError = ErrorResponse


export function useGetApiAdminSuggestionsRejected<TData = Awaited<ReturnType<typeof getApiAdminSuggestionsRejected>>, TError = ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminSuggestionsRejected>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAdminSuggestionsRejected>>,
          TError,
          Awaited<ReturnType<typeof getApiAdminSuggestionsRejected>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAdminSuggestionsRejected<TData = Awaited<ReturnType<typeof getApiAdminSuggestionsRejected>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminSuggestionsRejected>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAdminSuggestionsRejected>>,
          TError,
          Awaited<ReturnType<typeof getApiAdminSuggestionsRejected>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAdminSuggestionsRejected<TData = Awaited<ReturnType<typeof getApiAdminSuggestionsRejected>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminSuggestionsRejected>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary The rejected archive: rejected suggestions, newest rejection first
 */

export function useGetApiAdminSuggestionsRejected<TData = Awaited<ReturnType<typeof getApiAdminSuggestionsRejected>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminSuggestionsRejected>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAdminSuggestionsRejectedQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Restore a rejected suggestion back to the pending queue
 */
export const postApiAdminSuggestionsIdRestore = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return apiFetch<Suggestion>(
      {url: `/api/admin/suggestions/${id}/restore`, method: 'POST', ...(signal ? { signal }: {})
    },
      );
    }
  


export const getPostApiAdminSuggestionsIdRestoreMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAdminSuggestionsIdRestore>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiAdminSuggestionsIdRestore>>, TError,{id: string}, TContext> => {

const mutationKey = ['postApiAdminSuggestionsIdRestore'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAdminSuggestionsIdRestore>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  postApiAdminSuggestionsIdRestore(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiAdminSuggestionsIdRestoreMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAdminSuggestionsIdRestore>>>
    
    export type PostApiAdminSuggestionsIdRestoreMutationError = ErrorResponse

    /**
 * @summary Restore a rejected suggestion back to the pending queue
 */
export const usePostApiAdminSuggestionsIdRestore = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAdminSuggestionsIdRestore>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAdminSuggestionsIdRestore>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getPostApiAdminSuggestionsIdRestoreMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary The Ehdotusjono: unprocessed reader links, newest first
 */
export const getApiAdminSubmissions = (
    
 signal?: AbortSignal
) => {
      
      
      return apiFetch<UrlSubmission[]>(
      {url: `/api/admin/submissions`, method: 'GET', ...(signal ? { signal }: {})
    },
      );
    }
  



export const getGetApiAdminSubmissionsQueryKey = () => {
    return [
    `/api/admin/submissions`
    ] as const;
    }

    
export const getGetApiAdminSubmissionsQueryOptions = <TData = Awaited<ReturnType<typeof getApiAdminSubmissions>>, TError = ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminSubmissions>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAdminSubmissionsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAdminSubmissions>>> = ({ signal }) => getApiAdminSubmissions(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAdminSubmissions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAdminSubmissionsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAdminSubmissions>>>
export type GetApiAdminSubmissionsQueryError = ErrorResponse


export function useGetApiAdminSubmissions<TData = Awaited<ReturnType<typeof getApiAdminSubmissions>>, TError = ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminSubmissions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAdminSubmissions>>,
          TError,
          Awaited<ReturnType<typeof getApiAdminSubmissions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAdminSubmissions<TData = Awaited<ReturnType<typeof getApiAdminSubmissions>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminSubmissions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAdminSubmissions>>,
          TError,
          Awaited<ReturnType<typeof getApiAdminSubmissions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAdminSubmissions<TData = Awaited<ReturnType<typeof getApiAdminSubmissions>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminSubmissions>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary The Ehdotusjono: unprocessed reader links, newest first
 */

export function useGetApiAdminSubmissions<TData = Awaited<ReturnType<typeof getApiAdminSubmissions>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminSubmissions>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAdminSubmissionsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Send a submission to the AI queue (creates a pending suggestion)
 */
export const postApiAdminSubmissionsIdProcess = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return apiFetch<PostApiAdminSubmissionsIdProcess200>(
      {url: `/api/admin/submissions/${id}/process`, method: 'POST', ...(signal ? { signal }: {})
    },
      );
    }
  


export const getPostApiAdminSubmissionsIdProcessMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAdminSubmissionsIdProcess>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiAdminSubmissionsIdProcess>>, TError,{id: string}, TContext> => {

const mutationKey = ['postApiAdminSubmissionsIdProcess'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAdminSubmissionsIdProcess>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  postApiAdminSubmissionsIdProcess(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiAdminSubmissionsIdProcessMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAdminSubmissionsIdProcess>>>
    
    export type PostApiAdminSubmissionsIdProcessMutationError = ErrorResponse

    /**
 * @summary Send a submission to the AI queue (creates a pending suggestion)
 */
export const usePostApiAdminSubmissionsIdProcess = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAdminSubmissionsIdProcess>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAdminSubmissionsIdProcess>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getPostApiAdminSubmissionsIdProcessMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary The page text (Markdown) archived at submit time
 */
export const getApiAdminSubmissionsIdArchiveText = (
    id: string,
    params?: GetApiAdminSubmissionsIdArchiveTextParams,
 signal?: AbortSignal
) => {
      
      
      return apiFetch<string>(
      {url: `/api/admin/submissions/${id}/archive/text`, method: 'GET',
        params, ...(signal ? { signal }: {})
    },
      );
    }
  



export const getGetApiAdminSubmissionsIdArchiveTextQueryKey = (id?: string,
    params?: GetApiAdminSubmissionsIdArchiveTextParams,) => {
    return [
    `/api/admin/submissions/${id}/archive/text`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiAdminSubmissionsIdArchiveTextQueryOptions = <TData = Awaited<ReturnType<typeof getApiAdminSubmissionsIdArchiveText>>, TError = ErrorResponse>(id: string,
    params?: GetApiAdminSubmissionsIdArchiveTextParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminSubmissionsIdArchiveText>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAdminSubmissionsIdArchiveTextQueryKey(id,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAdminSubmissionsIdArchiveText>>> = ({ signal }) => getApiAdminSubmissionsIdArchiveText(id,params, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAdminSubmissionsIdArchiveText>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAdminSubmissionsIdArchiveTextQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAdminSubmissionsIdArchiveText>>>
export type GetApiAdminSubmissionsIdArchiveTextQueryError = ErrorResponse


export function useGetApiAdminSubmissionsIdArchiveText<TData = Awaited<ReturnType<typeof getApiAdminSubmissionsIdArchiveText>>, TError = ErrorResponse>(
 id: string,
    params: undefined |  GetApiAdminSubmissionsIdArchiveTextParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminSubmissionsIdArchiveText>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAdminSubmissionsIdArchiveText>>,
          TError,
          Awaited<ReturnType<typeof getApiAdminSubmissionsIdArchiveText>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAdminSubmissionsIdArchiveText<TData = Awaited<ReturnType<typeof getApiAdminSubmissionsIdArchiveText>>, TError = ErrorResponse>(
 id: string,
    params?: GetApiAdminSubmissionsIdArchiveTextParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminSubmissionsIdArchiveText>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAdminSubmissionsIdArchiveText>>,
          TError,
          Awaited<ReturnType<typeof getApiAdminSubmissionsIdArchiveText>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAdminSubmissionsIdArchiveText<TData = Awaited<ReturnType<typeof getApiAdminSubmissionsIdArchiveText>>, TError = ErrorResponse>(
 id: string,
    params?: GetApiAdminSubmissionsIdArchiveTextParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminSubmissionsIdArchiveText>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary The page text (Markdown) archived at submit time
 */

export function useGetApiAdminSubmissionsIdArchiveText<TData = Awaited<ReturnType<typeof getApiAdminSubmissionsIdArchiveText>>, TError = ErrorResponse>(
 id: string,
    params?: GetApiAdminSubmissionsIdArchiveTextParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminSubmissionsIdArchiveText>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAdminSubmissionsIdArchiveTextQueryOptions(id,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Save a manually edited archive text (e.g. a pasted paywalled article)
 */
export const putApiAdminSubmissionsIdArchiveText = (
    id: string,
    archiveTextEdit: ArchiveTextEdit,
 ) => {
      
      
      return apiFetch<PutApiAdminSubmissionsIdArchiveText200>(
      {url: `/api/admin/submissions/${id}/archive/text`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: archiveTextEdit
    },
      );
    }
  


export const getPutApiAdminSubmissionsIdArchiveTextMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiAdminSubmissionsIdArchiveText>>, TError,{id: string;data: ArchiveTextEdit}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putApiAdminSubmissionsIdArchiveText>>, TError,{id: string;data: ArchiveTextEdit}, TContext> => {

const mutationKey = ['putApiAdminSubmissionsIdArchiveText'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiAdminSubmissionsIdArchiveText>>, {id: string;data: ArchiveTextEdit}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiAdminSubmissionsIdArchiveText(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiAdminSubmissionsIdArchiveTextMutationResult = NonNullable<Awaited<ReturnType<typeof putApiAdminSubmissionsIdArchiveText>>>
    export type PutApiAdminSubmissionsIdArchiveTextMutationBody = ArchiveTextEdit
    export type PutApiAdminSubmissionsIdArchiveTextMutationError = ErrorResponse

    /**
 * @summary Save a manually edited archive text (e.g. a pasted paywalled article)
 */
export const usePutApiAdminSubmissionsIdArchiveText = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiAdminSubmissionsIdArchiveText>>, TError,{id: string;data: ArchiveTextEdit}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiAdminSubmissionsIdArchiveText>>,
        TError,
        {id: string;data: ArchiveTextEdit},
        TContext
      > => {

      const mutationOptions = getPutApiAdminSubmissionsIdArchiveTextMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Reject a link out of the Ehdotusjono
 */
export const postApiAdminSubmissionsIdReject = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return apiFetch<PostApiAdminSubmissionsIdReject200>(
      {url: `/api/admin/submissions/${id}/reject`, method: 'POST', ...(signal ? { signal }: {})
    },
      );
    }
  


export const getPostApiAdminSubmissionsIdRejectMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAdminSubmissionsIdReject>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiAdminSubmissionsIdReject>>, TError,{id: string}, TContext> => {

const mutationKey = ['postApiAdminSubmissionsIdReject'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAdminSubmissionsIdReject>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  postApiAdminSubmissionsIdReject(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiAdminSubmissionsIdRejectMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAdminSubmissionsIdReject>>>
    
    export type PostApiAdminSubmissionsIdRejectMutationError = ErrorResponse

    /**
 * @summary Reject a link out of the Ehdotusjono
 */
export const usePostApiAdminSubmissionsIdReject = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAdminSubmissionsIdReject>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAdminSubmissionsIdReject>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getPostApiAdminSubmissionsIdRejectMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary The rejected-links archive, newest rejection first
 */
export const getApiAdminSubmissionsRejected = (
    
 signal?: AbortSignal
) => {
      
      
      return apiFetch<RejectedUrlSubmission[]>(
      {url: `/api/admin/submissions/rejected`, method: 'GET', ...(signal ? { signal }: {})
    },
      );
    }
  



export const getGetApiAdminSubmissionsRejectedQueryKey = () => {
    return [
    `/api/admin/submissions/rejected`
    ] as const;
    }

    
export const getGetApiAdminSubmissionsRejectedQueryOptions = <TData = Awaited<ReturnType<typeof getApiAdminSubmissionsRejected>>, TError = ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminSubmissionsRejected>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAdminSubmissionsRejectedQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAdminSubmissionsRejected>>> = ({ signal }) => getApiAdminSubmissionsRejected(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAdminSubmissionsRejected>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAdminSubmissionsRejectedQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAdminSubmissionsRejected>>>
export type GetApiAdminSubmissionsRejectedQueryError = ErrorResponse


export function useGetApiAdminSubmissionsRejected<TData = Awaited<ReturnType<typeof getApiAdminSubmissionsRejected>>, TError = ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminSubmissionsRejected>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAdminSubmissionsRejected>>,
          TError,
          Awaited<ReturnType<typeof getApiAdminSubmissionsRejected>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAdminSubmissionsRejected<TData = Awaited<ReturnType<typeof getApiAdminSubmissionsRejected>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminSubmissionsRejected>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAdminSubmissionsRejected>>,
          TError,
          Awaited<ReturnType<typeof getApiAdminSubmissionsRejected>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAdminSubmissionsRejected<TData = Awaited<ReturnType<typeof getApiAdminSubmissionsRejected>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminSubmissionsRejected>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary The rejected-links archive, newest rejection first
 */

export function useGetApiAdminSubmissionsRejected<TData = Awaited<ReturnType<typeof getApiAdminSubmissionsRejected>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminSubmissionsRejected>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAdminSubmissionsRejectedQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Restore a rejected link back to the Ehdotusjono
 */
export const postApiAdminSubmissionsIdRestore = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return apiFetch<UrlSubmission>(
      {url: `/api/admin/submissions/${id}/restore`, method: 'POST', ...(signal ? { signal }: {})
    },
      );
    }
  


export const getPostApiAdminSubmissionsIdRestoreMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAdminSubmissionsIdRestore>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiAdminSubmissionsIdRestore>>, TError,{id: string}, TContext> => {

const mutationKey = ['postApiAdminSubmissionsIdRestore'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAdminSubmissionsIdRestore>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  postApiAdminSubmissionsIdRestore(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiAdminSubmissionsIdRestoreMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAdminSubmissionsIdRestore>>>
    
    export type PostApiAdminSubmissionsIdRestoreMutationError = ErrorResponse

    /**
 * @summary Restore a rejected link back to the Ehdotusjono
 */
export const usePostApiAdminSubmissionsIdRestore = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAdminSubmissionsIdRestore>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAdminSubmissionsIdRestore>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getPostApiAdminSubmissionsIdRestoreMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    