/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Rahaaon API
 * Crowdsourced tracker of wasteful public spending (rahaaon.fi).
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorResponse,
  PatchApiAdminItemsId200,
  PatchItem,
  PatchSuggestion,
  PostApiAdminSuggestionsIdApprove200,
  PostApiAdminSuggestionsIdReject200,
  Suggestion,
  WasteItem
} from '.././model';

import { apiFetch } from '../../lib/api-fetch';




/**
 * @summary All published items including hidden ones (editorial)
 */
export const getApiAdminItems = (
    
 signal?: AbortSignal
) => {
      
      
      return apiFetch<WasteItem[]>(
      {url: `/api/admin/items`, method: 'GET', ...(signal ? { signal }: {})
    },
      );
    }
  



export const getGetApiAdminItemsQueryKey = () => {
    return [
    `/api/admin/items`
    ] as const;
    }

    
export const getGetApiAdminItemsQueryOptions = <TData = Awaited<ReturnType<typeof getApiAdminItems>>, TError = ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminItems>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAdminItemsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAdminItems>>> = ({ signal }) => getApiAdminItems(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAdminItems>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAdminItemsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAdminItems>>>
export type GetApiAdminItemsQueryError = ErrorResponse


export function useGetApiAdminItems<TData = Awaited<ReturnType<typeof getApiAdminItems>>, TError = ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminItems>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAdminItems>>,
          TError,
          Awaited<ReturnType<typeof getApiAdminItems>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAdminItems<TData = Awaited<ReturnType<typeof getApiAdminItems>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminItems>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAdminItems>>,
          TError,
          Awaited<ReturnType<typeof getApiAdminItems>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAdminItems<TData = Awaited<ReturnType<typeof getApiAdminItems>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminItems>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary All published items including hidden ones (editorial)
 */

export function useGetApiAdminItems<TData = Awaited<ReturnType<typeof getApiAdminItems>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminItems>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAdminItemsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Hide an item from the feed, or restore it (editorial)
 */
export const patchApiAdminItemsId = (
    id: string,
    patchItem: PatchItem,
 ) => {
      
      
      return apiFetch<PatchApiAdminItemsId200>(
      {url: `/api/admin/items/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchItem
    },
      );
    }
  


export const getPatchApiAdminItemsIdMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiAdminItemsId>>, TError,{id: string;data: PatchItem}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof patchApiAdminItemsId>>, TError,{id: string;data: PatchItem}, TContext> => {

const mutationKey = ['patchApiAdminItemsId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiAdminItemsId>>, {id: string;data: PatchItem}> = (props) => {
          const {id,data} = props ?? {};

          return  patchApiAdminItemsId(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiAdminItemsIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiAdminItemsId>>>
    export type PatchApiAdminItemsIdMutationBody = PatchItem
    export type PatchApiAdminItemsIdMutationError = ErrorResponse

    /**
 * @summary Hide an item from the feed, or restore it (editorial)
 */
export const usePatchApiAdminItemsId = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiAdminItemsId>>, TError,{id: string;data: PatchItem}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiAdminItemsId>>,
        TError,
        {id: string;data: PatchItem},
        TContext
      > => {

      const mutationOptions = getPatchApiAdminItemsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary The editorial queue: pending suggestions, newest first
 */
export const getApiAdminSuggestions = (
    
 signal?: AbortSignal
) => {
      
      
      return apiFetch<Suggestion[]>(
      {url: `/api/admin/suggestions`, method: 'GET', ...(signal ? { signal }: {})
    },
      );
    }
  



export const getGetApiAdminSuggestionsQueryKey = () => {
    return [
    `/api/admin/suggestions`
    ] as const;
    }

    
export const getGetApiAdminSuggestionsQueryOptions = <TData = Awaited<ReturnType<typeof getApiAdminSuggestions>>, TError = ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminSuggestions>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAdminSuggestionsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAdminSuggestions>>> = ({ signal }) => getApiAdminSuggestions(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAdminSuggestions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAdminSuggestionsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAdminSuggestions>>>
export type GetApiAdminSuggestionsQueryError = ErrorResponse


export function useGetApiAdminSuggestions<TData = Awaited<ReturnType<typeof getApiAdminSuggestions>>, TError = ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminSuggestions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAdminSuggestions>>,
          TError,
          Awaited<ReturnType<typeof getApiAdminSuggestions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAdminSuggestions<TData = Awaited<ReturnType<typeof getApiAdminSuggestions>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminSuggestions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAdminSuggestions>>,
          TError,
          Awaited<ReturnType<typeof getApiAdminSuggestions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAdminSuggestions<TData = Awaited<ReturnType<typeof getApiAdminSuggestions>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminSuggestions>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary The editorial queue: pending suggestions, newest first
 */

export function useGetApiAdminSuggestions<TData = Awaited<ReturnType<typeof getApiAdminSuggestions>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAdminSuggestions>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAdminSuggestionsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Apply editorial edits to a pending suggestion
 */
export const patchApiAdminSuggestionsId = (
    id: string,
    patchSuggestion: PatchSuggestion,
 ) => {
      
      
      return apiFetch<Suggestion>(
      {url: `/api/admin/suggestions/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchSuggestion
    },
      );
    }
  


export const getPatchApiAdminSuggestionsIdMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiAdminSuggestionsId>>, TError,{id: string;data: PatchSuggestion}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof patchApiAdminSuggestionsId>>, TError,{id: string;data: PatchSuggestion}, TContext> => {

const mutationKey = ['patchApiAdminSuggestionsId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiAdminSuggestionsId>>, {id: string;data: PatchSuggestion}> = (props) => {
          const {id,data} = props ?? {};

          return  patchApiAdminSuggestionsId(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiAdminSuggestionsIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiAdminSuggestionsId>>>
    export type PatchApiAdminSuggestionsIdMutationBody = PatchSuggestion
    export type PatchApiAdminSuggestionsIdMutationError = ErrorResponse

    /**
 * @summary Apply editorial edits to a pending suggestion
 */
export const usePatchApiAdminSuggestionsId = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiAdminSuggestionsId>>, TError,{id: string;data: PatchSuggestion}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiAdminSuggestionsId>>,
        TError,
        {id: string;data: PatchSuggestion},
        TContext
      > => {

      const mutationOptions = getPatchApiAdminSuggestionsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Publish a pending suggestion to the feed
 */
export const postApiAdminSuggestionsIdApprove = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return apiFetch<PostApiAdminSuggestionsIdApprove200>(
      {url: `/api/admin/suggestions/${id}/approve`, method: 'POST', ...(signal ? { signal }: {})
    },
      );
    }
  


export const getPostApiAdminSuggestionsIdApproveMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAdminSuggestionsIdApprove>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiAdminSuggestionsIdApprove>>, TError,{id: string}, TContext> => {

const mutationKey = ['postApiAdminSuggestionsIdApprove'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAdminSuggestionsIdApprove>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  postApiAdminSuggestionsIdApprove(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiAdminSuggestionsIdApproveMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAdminSuggestionsIdApprove>>>
    
    export type PostApiAdminSuggestionsIdApproveMutationError = ErrorResponse

    /**
 * @summary Publish a pending suggestion to the feed
 */
export const usePostApiAdminSuggestionsIdApprove = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAdminSuggestionsIdApprove>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAdminSuggestionsIdApprove>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getPostApiAdminSuggestionsIdApproveMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Reject a pending suggestion
 */
export const postApiAdminSuggestionsIdReject = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return apiFetch<PostApiAdminSuggestionsIdReject200>(
      {url: `/api/admin/suggestions/${id}/reject`, method: 'POST', ...(signal ? { signal }: {})
    },
      );
    }
  


export const getPostApiAdminSuggestionsIdRejectMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAdminSuggestionsIdReject>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiAdminSuggestionsIdReject>>, TError,{id: string}, TContext> => {

const mutationKey = ['postApiAdminSuggestionsIdReject'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAdminSuggestionsIdReject>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  postApiAdminSuggestionsIdReject(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiAdminSuggestionsIdRejectMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAdminSuggestionsIdReject>>>
    
    export type PostApiAdminSuggestionsIdRejectMutationError = ErrorResponse

    /**
 * @summary Reject a pending suggestion
 */
export const usePostApiAdminSuggestionsIdReject = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAdminSuggestionsIdReject>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAdminSuggestionsIdReject>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getPostApiAdminSuggestionsIdRejectMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    