/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Rahaaon API
 * Crowdsourced tracker of wasteful public spending (rahaaon.fi).
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorResponse,
  VoteResult,
  WasteItem
} from '.././model';

import { apiFetch } from '../../lib/api-fetch';




/**
 * @summary Published feed items (visible only), newest first
 */
export const getApiItems = (
    
 signal?: AbortSignal
) => {
      
      
      return apiFetch<WasteItem[]>(
      {url: `/api/items`, method: 'GET', ...(signal ? { signal }: {})
    },
      );
    }
  



export const getGetApiItemsQueryKey = () => {
    return [
    `/api/items`
    ] as const;
    }

    
export const getGetApiItemsQueryOptions = <TData = Awaited<ReturnType<typeof getApiItems>>, TError = ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiItems>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiItemsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiItems>>> = ({ signal }) => getApiItems(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiItems>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiItemsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiItems>>>
export type GetApiItemsQueryError = ErrorResponse


export function useGetApiItems<TData = Awaited<ReturnType<typeof getApiItems>>, TError = ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiItems>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiItems>>,
          TError,
          Awaited<ReturnType<typeof getApiItems>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiItems<TData = Awaited<ReturnType<typeof getApiItems>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiItems>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiItems>>,
          TError,
          Awaited<ReturnType<typeof getApiItems>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiItems<TData = Awaited<ReturnType<typeof getApiItems>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiItems>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Published feed items (visible only), newest first
 */

export function useGetApiItems<TData = Awaited<ReturnType<typeof getApiItems>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiItems>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiItemsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Toggle the visitor's "this is a waste" vote
 */
export const postApiItemsIdVote = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return apiFetch<VoteResult>(
      {url: `/api/items/${id}/vote`, method: 'POST', ...(signal ? { signal }: {})
    },
      );
    }
  


export const getPostApiItemsIdVoteMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiItemsIdVote>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiItemsIdVote>>, TError,{id: string}, TContext> => {

const mutationKey = ['postApiItemsIdVote'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiItemsIdVote>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  postApiItemsIdVote(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiItemsIdVoteMutationResult = NonNullable<Awaited<ReturnType<typeof postApiItemsIdVote>>>
    
    export type PostApiItemsIdVoteMutationError = ErrorResponse

    /**
 * @summary Toggle the visitor's "this is a waste" vote
 */
export const usePostApiItemsIdVote = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiItemsIdVote>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiItemsIdVote>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getPostApiItemsIdVoteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    