/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Rahaaon API
 * Crowdsourced tracker of wasteful public spending (rahaaon.fi).
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  ErrorResponse,
  PostApiSuggestions201,
  SuggestUrl,
  SuggestionPreview
} from '.././model';

import { apiFetch } from '../../lib/api-fetch';




/**
 * @summary Run the AI extraction for a link, without submitting anything
 */
export const postApiSuggestionsPreview = (
    suggestUrl: SuggestUrl,
 signal?: AbortSignal
) => {
      
      
      return apiFetch<SuggestionPreview>(
      {url: `/api/suggestions/preview`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: suggestUrl, ...(signal ? { signal }: {})
    },
      );
    }
  


export const getPostApiSuggestionsPreviewMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiSuggestionsPreview>>, TError,{data: SuggestUrl}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiSuggestionsPreview>>, TError,{data: SuggestUrl}, TContext> => {

const mutationKey = ['postApiSuggestionsPreview'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiSuggestionsPreview>>, {data: SuggestUrl}> = (props) => {
          const {data} = props ?? {};

          return  postApiSuggestionsPreview(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiSuggestionsPreviewMutationResult = NonNullable<Awaited<ReturnType<typeof postApiSuggestionsPreview>>>
    export type PostApiSuggestionsPreviewMutationBody = SuggestUrl
    export type PostApiSuggestionsPreviewMutationError = ErrorResponse

    /**
 * @summary Run the AI extraction for a link, without submitting anything
 */
export const usePostApiSuggestionsPreview = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiSuggestionsPreview>>, TError,{data: SuggestUrl}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiSuggestionsPreview>>,
        TError,
        {data: SuggestUrl},
        TContext
      > => {

      const mutationOptions = getPostApiSuggestionsPreviewMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Submit a link to the editorial queue (anonymous)
 */
export const postApiSuggestions = (
    suggestUrl: SuggestUrl,
 signal?: AbortSignal
) => {
      
      
      return apiFetch<PostApiSuggestions201>(
      {url: `/api/suggestions`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: suggestUrl, ...(signal ? { signal }: {})
    },
      );
    }
  


export const getPostApiSuggestionsMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiSuggestions>>, TError,{data: SuggestUrl}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiSuggestions>>, TError,{data: SuggestUrl}, TContext> => {

const mutationKey = ['postApiSuggestions'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiSuggestions>>, {data: SuggestUrl}> = (props) => {
          const {data} = props ?? {};

          return  postApiSuggestions(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiSuggestionsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiSuggestions>>>
    export type PostApiSuggestionsMutationBody = SuggestUrl
    export type PostApiSuggestionsMutationError = ErrorResponse

    /**
 * @summary Submit a link to the editorial queue (anonymous)
 */
export const usePostApiSuggestions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiSuggestions>>, TError,{data: SuggestUrl}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiSuggestions>>,
        TError,
        {data: SuggestUrl},
        TContext
      > => {

      const mutationOptions = getPostApiSuggestionsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    