/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Rahaaon API
 * Crowdsourced tracker of wasteful public spending (rahaaon.fi).
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorResponse,
  Health,
  Readiness
} from '.././model';

import { apiFetch } from '../../lib/api-fetch';




/**
 * @summary Liveness probe
 */
export const getApiHealth = (
    
 signal?: AbortSignal
) => {
      
      
      return apiFetch<Health>(
      {url: `/api/health`, method: 'GET', ...(signal ? { signal }: {})
    },
      );
    }
  



export const getGetApiHealthQueryKey = () => {
    return [
    `/api/health`
    ] as const;
    }

    
export const getGetApiHealthQueryOptions = <TData = Awaited<ReturnType<typeof getApiHealth>>, TError = ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiHealth>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiHealthQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiHealth>>> = ({ signal }) => getApiHealth(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiHealth>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiHealthQueryResult = NonNullable<Awaited<ReturnType<typeof getApiHealth>>>
export type GetApiHealthQueryError = ErrorResponse


export function useGetApiHealth<TData = Awaited<ReturnType<typeof getApiHealth>>, TError = ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiHealth>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiHealth>>,
          TError,
          Awaited<ReturnType<typeof getApiHealth>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiHealth<TData = Awaited<ReturnType<typeof getApiHealth>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiHealth>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiHealth>>,
          TError,
          Awaited<ReturnType<typeof getApiHealth>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiHealth<TData = Awaited<ReturnType<typeof getApiHealth>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiHealth>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Liveness probe
 */

export function useGetApiHealth<TData = Awaited<ReturnType<typeof getApiHealth>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiHealth>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiHealthQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Readiness probe (checks the database)
 */
export const getApiHealthReady = (
    
 signal?: AbortSignal
) => {
      
      
      return apiFetch<Readiness>(
      {url: `/api/health/ready`, method: 'GET', ...(signal ? { signal }: {})
    },
      );
    }
  



export const getGetApiHealthReadyQueryKey = () => {
    return [
    `/api/health/ready`
    ] as const;
    }

    
export const getGetApiHealthReadyQueryOptions = <TData = Awaited<ReturnType<typeof getApiHealthReady>>, TError = Readiness>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiHealthReady>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiHealthReadyQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiHealthReady>>> = ({ signal }) => getApiHealthReady(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiHealthReady>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiHealthReadyQueryResult = NonNullable<Awaited<ReturnType<typeof getApiHealthReady>>>
export type GetApiHealthReadyQueryError = Readiness


export function useGetApiHealthReady<TData = Awaited<ReturnType<typeof getApiHealthReady>>, TError = Readiness>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiHealthReady>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiHealthReady>>,
          TError,
          Awaited<ReturnType<typeof getApiHealthReady>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiHealthReady<TData = Awaited<ReturnType<typeof getApiHealthReady>>, TError = Readiness>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiHealthReady>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiHealthReady>>,
          TError,
          Awaited<ReturnType<typeof getApiHealthReady>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiHealthReady<TData = Awaited<ReturnType<typeof getApiHealthReady>>, TError = Readiness>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiHealthReady>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Readiness probe (checks the database)
 */

export function useGetApiHealthReady<TData = Awaited<ReturnType<typeof getApiHealthReady>>, TError = Readiness>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiHealthReady>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiHealthReadyQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




