/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Rahaaon API
 * Crowdsourced tracker of wasteful public spending (rahaaon.fi).
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  ErrorResponse,
  PagePreview,
  PostApiSubmissions201,
  SubmitUrl
} from '.././model';

import { apiFetch } from '../../lib/api-fetch';




/**
 * @summary Fetch the google-like page preview for a link, without submitting anything
 */
export const postApiSubmissionsPreview = (
    submitUrl: SubmitUrl,
 signal?: AbortSignal
) => {
      
      
      return apiFetch<PagePreview>(
      {url: `/api/submissions/preview`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: submitUrl, ...(signal ? { signal }: {})
    },
      );
    }
  


export const getPostApiSubmissionsPreviewMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiSubmissionsPreview>>, TError,{data: SubmitUrl}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiSubmissionsPreview>>, TError,{data: SubmitUrl}, TContext> => {

const mutationKey = ['postApiSubmissionsPreview'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiSubmissionsPreview>>, {data: SubmitUrl}> = (props) => {
          const {data} = props ?? {};

          return  postApiSubmissionsPreview(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiSubmissionsPreviewMutationResult = NonNullable<Awaited<ReturnType<typeof postApiSubmissionsPreview>>>
    export type PostApiSubmissionsPreviewMutationBody = SubmitUrl
    export type PostApiSubmissionsPreviewMutationError = ErrorResponse

    /**
 * @summary Fetch the google-like page preview for a link, without submitting anything
 */
export const usePostApiSubmissionsPreview = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiSubmissionsPreview>>, TError,{data: SubmitUrl}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiSubmissionsPreview>>,
        TError,
        {data: SubmitUrl},
        TContext
      > => {

      const mutationOptions = getPostApiSubmissionsPreviewMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Submit a confirmed link to the Ehdotusjono (anonymous)
 */
export const postApiSubmissions = (
    submitUrl: SubmitUrl,
 signal?: AbortSignal
) => {
      
      
      return apiFetch<PostApiSubmissions201>(
      {url: `/api/submissions`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: submitUrl, ...(signal ? { signal }: {})
    },
      );
    }
  


export const getPostApiSubmissionsMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiSubmissions>>, TError,{data: SubmitUrl}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiSubmissions>>, TError,{data: SubmitUrl}, TContext> => {

const mutationKey = ['postApiSubmissions'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiSubmissions>>, {data: SubmitUrl}> = (props) => {
          const {data} = props ?? {};

          return  postApiSubmissions(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiSubmissionsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiSubmissions>>>
    export type PostApiSubmissionsMutationBody = SubmitUrl
    export type PostApiSubmissionsMutationError = ErrorResponse

    /**
 * @summary Submit a confirmed link to the Ehdotusjono (anonymous)
 */
export const usePostApiSubmissions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiSubmissions>>, TError,{data: SubmitUrl}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiSubmissions>>,
        TError,
        {data: SubmitUrl},
        TContext
      > => {

      const mutationOptions = getPostApiSubmissionsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    