/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Rahaaon API
 * Crowdsourced tracker of wasteful public spending (rahaaon.fi).
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';

/**
 * @summary Liveness probe
 */
export const getApiHealthResponse = zod.object({
  "status": zod.enum(['ok'])
})


/**
 * @summary Readiness probe (checks the database)
 */
export const getApiHealthReadyResponse = zod.object({
  "status": zod.enum(['ok', 'degraded']),
  "db": zod.enum(['up', 'down'])
})


/**
 * @summary Current editorial user, or null when not signed in
 */
export const getApiMeResponse = zod.union([zod.object({
  "user": zod.object({
  "id": zod.string(),
  "email": zod.string(),
  "name": zod.string()
})
}),zod.null()])


/**
 * @summary Published feed items (visible only), newest first
 */
export const getApiItemsResponseItem = zod.object({
  "id": zod.uuid(),
  "title": zod.string(),
  "amountEur": zod.number(),
  "amountType": zod.enum(['exact', 'approx', 'min', 'unknown']),
  "amountMaxEur": zod.number().nullable(),
  "entity": zod.string(),
  "category": zod.enum(['Rakentaminen', 'IT-hankkeet', 'Konsultit', 'Kulttuuri', 'Viestintä', 'Matkustus', 'Muu']),
  "sourceName": zod.string(),
  "sourceUrl": zod.string(),
  "summary": zod.string(),
  "quote": zod.string(),
  "hidden": zod.boolean(),
  "publishedAt": zod.iso.datetime({}),
  "articlePublishedAt": zod.iso.date().nullable(),
  "votes": zod.number(),
  "voted": zod.boolean()
})
export const getApiItemsResponse = zod.array(getApiItemsResponseItem)


/**
 * @summary Toggle the visitor's "this is a waste" vote
 */
export const postApiItemsIdVoteParams = zod.object({
  "id": zod.uuid()
})

export const postApiItemsIdVoteResponse = zod.object({
  "votes": zod.number(),
  "voted": zod.boolean()
})


/**
 * @summary All published items including hidden ones (editorial)
 */
export const getApiAdminItemsResponseItem = zod.object({
  "id": zod.uuid(),
  "title": zod.string(),
  "amountEur": zod.number(),
  "amountType": zod.enum(['exact', 'approx', 'min', 'unknown']),
  "amountMaxEur": zod.number().nullable(),
  "entity": zod.string(),
  "category": zod.enum(['Rakentaminen', 'IT-hankkeet', 'Konsultit', 'Kulttuuri', 'Viestintä', 'Matkustus', 'Muu']),
  "sourceName": zod.string(),
  "sourceUrl": zod.string(),
  "summary": zod.string(),
  "quote": zod.string(),
  "hidden": zod.boolean(),
  "publishedAt": zod.iso.datetime({}),
  "articlePublishedAt": zod.iso.date().nullable(),
  "votes": zod.number(),
  "voted": zod.boolean()
})
export const getApiAdminItemsResponse = zod.array(getApiAdminItemsResponseItem)


/**
 * @summary Apply editorial edits to a published item, hiding/restoring included
 */
export const patchApiAdminItemsIdParams = zod.object({
  "id": zod.uuid()
})

export const patchApiAdminItemsIdBodyTitleMax = 300;

export const patchApiAdminItemsIdBodySummaryMax = 2000;

export const patchApiAdminItemsIdBodyQuoteMax = 500;

export const patchApiAdminItemsIdBodyAmountEurMin = 0;

export const patchApiAdminItemsIdBodyAmountMaxEurMin = 0;

export const patchApiAdminItemsIdBodyEntityMax = 120;



export const patchApiAdminItemsIdBody = zod.object({
  "title": zod.string().min(1).max(patchApiAdminItemsIdBodyTitleMax).optional(),
  "summary": zod.string().min(1).max(patchApiAdminItemsIdBodySummaryMax).optional(),
  "quote": zod.string().max(patchApiAdminItemsIdBodyQuoteMax).optional(),
  "amountEur": zod.number().min(patchApiAdminItemsIdBodyAmountEurMin).optional(),
  "amountType": zod.enum(['exact', 'approx', 'min', 'unknown']).optional(),
  "amountMaxEur": zod.number().min(patchApiAdminItemsIdBodyAmountMaxEurMin).nullish(),
  "entity": zod.string().min(1).max(patchApiAdminItemsIdBodyEntityMax).optional(),
  "category": zod.enum(['Rakentaminen', 'IT-hankkeet', 'Konsultit', 'Kulttuuri', 'Viestintä', 'Matkustus', 'Muu']).optional(),
  "articlePublishedAt": zod.iso.date().nullish(),
  "hidden": zod.boolean().optional()
})

export const patchApiAdminItemsIdResponse = zod.object({
  "ok": zod.literal(true)
})


/**
 * @summary The AI queue: pending suggestions, newest first
 */
export const getApiAdminSuggestionsResponseItem = zod.object({
  "id": zod.uuid(),
  "url": zod.string(),
  "title": zod.string(),
  "amountEur": zod.number(),
  "amountType": zod.enum(['exact', 'approx', 'min', 'unknown']),
  "amountMaxEur": zod.number().nullable(),
  "entity": zod.string(),
  "category": zod.enum(['Rakentaminen', 'IT-hankkeet', 'Konsultit', 'Kulttuuri', 'Viestintä', 'Matkustus', 'Muu']),
  "sourceName": zod.string(),
  "articlePublishedAt": zod.iso.date().nullable(),
  "summary": zod.string(),
  "quote": zod.string(),
  "aiNote": zod.string(),
  "confidence": zod.number(),
  "createdAt": zod.iso.datetime({})
})
export const getApiAdminSuggestionsResponse = zod.array(getApiAdminSuggestionsResponseItem)


/**
 * @summary Apply editorial edits to a pending suggestion
 */
export const patchApiAdminSuggestionsIdParams = zod.object({
  "id": zod.uuid()
})

export const patchApiAdminSuggestionsIdBodyTitleMax = 300;

export const patchApiAdminSuggestionsIdBodySummaryMax = 2000;

export const patchApiAdminSuggestionsIdBodyQuoteMax = 500;

export const patchApiAdminSuggestionsIdBodyAmountEurMin = 0;

export const patchApiAdminSuggestionsIdBodyAmountMaxEurMin = 0;

export const patchApiAdminSuggestionsIdBodyEntityMax = 120;



export const patchApiAdminSuggestionsIdBody = zod.object({
  "title": zod.string().min(1).max(patchApiAdminSuggestionsIdBodyTitleMax).optional(),
  "summary": zod.string().min(1).max(patchApiAdminSuggestionsIdBodySummaryMax).optional(),
  "quote": zod.string().max(patchApiAdminSuggestionsIdBodyQuoteMax).optional(),
  "amountEur": zod.number().min(patchApiAdminSuggestionsIdBodyAmountEurMin).optional(),
  "amountType": zod.enum(['exact', 'approx', 'min', 'unknown']).optional(),
  "amountMaxEur": zod.number().min(patchApiAdminSuggestionsIdBodyAmountMaxEurMin).nullish(),
  "entity": zod.string().min(1).max(patchApiAdminSuggestionsIdBodyEntityMax).optional(),
  "category": zod.enum(['Rakentaminen', 'IT-hankkeet', 'Konsultit', 'Kulttuuri', 'Viestintä', 'Matkustus', 'Muu']).optional(),
  "articlePublishedAt": zod.iso.date().nullish()
})

export const patchApiAdminSuggestionsIdResponse = zod.object({
  "id": zod.uuid(),
  "url": zod.string(),
  "title": zod.string(),
  "amountEur": zod.number(),
  "amountType": zod.enum(['exact', 'approx', 'min', 'unknown']),
  "amountMaxEur": zod.number().nullable(),
  "entity": zod.string(),
  "category": zod.enum(['Rakentaminen', 'IT-hankkeet', 'Konsultit', 'Kulttuuri', 'Viestintä', 'Matkustus', 'Muu']),
  "sourceName": zod.string(),
  "articlePublishedAt": zod.iso.date().nullable(),
  "summary": zod.string(),
  "quote": zod.string(),
  "aiNote": zod.string(),
  "confidence": zod.number(),
  "createdAt": zod.iso.datetime({})
})


/**
 * @summary Publish a pending suggestion to the feed
 */
export const postApiAdminSuggestionsIdApproveParams = zod.object({
  "id": zod.uuid()
})

export const postApiAdminSuggestionsIdApproveResponse = zod.object({
  "itemId": zod.uuid()
})


/**
 * @summary Reject a pending suggestion
 */
export const postApiAdminSuggestionsIdRejectParams = zod.object({
  "id": zod.uuid()
})

export const postApiAdminSuggestionsIdRejectResponse = zod.object({
  "ok": zod.literal(true)
})


/**
 * @summary The rejected archive: rejected suggestions, newest rejection first
 */
export const getApiAdminSuggestionsRejectedResponseItem = zod.object({
  "id": zod.uuid(),
  "url": zod.string(),
  "title": zod.string(),
  "amountEur": zod.number(),
  "amountType": zod.enum(['exact', 'approx', 'min', 'unknown']),
  "amountMaxEur": zod.number().nullable(),
  "entity": zod.string(),
  "category": zod.enum(['Rakentaminen', 'IT-hankkeet', 'Konsultit', 'Kulttuuri', 'Viestintä', 'Matkustus', 'Muu']),
  "sourceName": zod.string(),
  "articlePublishedAt": zod.iso.date().nullable(),
  "summary": zod.string(),
  "quote": zod.string(),
  "aiNote": zod.string(),
  "confidence": zod.number(),
  "createdAt": zod.iso.datetime({})
}).and(zod.object({
  "rejectedAt": zod.iso.datetime({})
}))
export const getApiAdminSuggestionsRejectedResponse = zod.array(getApiAdminSuggestionsRejectedResponseItem)


/**
 * @summary Restore a rejected suggestion back to the pending queue
 */
export const postApiAdminSuggestionsIdRestoreParams = zod.object({
  "id": zod.uuid()
})

export const postApiAdminSuggestionsIdRestoreResponse = zod.object({
  "id": zod.uuid(),
  "url": zod.string(),
  "title": zod.string(),
  "amountEur": zod.number(),
  "amountType": zod.enum(['exact', 'approx', 'min', 'unknown']),
  "amountMaxEur": zod.number().nullable(),
  "entity": zod.string(),
  "category": zod.enum(['Rakentaminen', 'IT-hankkeet', 'Konsultit', 'Kulttuuri', 'Viestintä', 'Matkustus', 'Muu']),
  "sourceName": zod.string(),
  "articlePublishedAt": zod.iso.date().nullable(),
  "summary": zod.string(),
  "quote": zod.string(),
  "aiNote": zod.string(),
  "confidence": zod.number(),
  "createdAt": zod.iso.datetime({})
})


/**
 * @summary Fetch the google-like page preview for a link, without submitting anything
 */
export const postApiSubmissionsPreviewBodyUrlMax = 2000;



export const postApiSubmissionsPreviewBody = zod.object({
  "url": zod.url().max(postApiSubmissionsPreviewBodyUrlMax)
})

export const postApiSubmissionsPreviewResponse = zod.object({
  "url": zod.string(),
  "siteName": zod.string(),
  "title": zod.string(),
  "description": zod.string(),
  "fetched": zod.boolean()
})


/**
 * @summary Submit a confirmed link to the Ehdotusjono (anonymous)
 */
export const postApiSubmissionsBodyUrlMax = 2000;



export const postApiSubmissionsBody = zod.object({
  "url": zod.url().max(postApiSubmissionsBodyUrlMax)
})


/**
 * @summary The Ehdotusjono: unprocessed reader links, newest first
 */
export const getApiAdminSubmissionsResponseItem = zod.object({
  "id": zod.uuid(),
  "url": zod.string(),
  "title": zod.string(),
  "description": zod.string(),
  "siteName": zod.string(),
  "createdAt": zod.iso.datetime({}),
  "archiveStatus": zod.union([zod.literal('pending'),zod.literal('ok'),zod.literal('paywalled'),zod.literal('failed'),zod.literal(null)]).nullable(),
  "hasArchivedText": zod.boolean(),
  "processing": zod.boolean(),
  "processError": zod.string().nullable()
})
export const getApiAdminSubmissionsResponse = zod.array(getApiAdminSubmissionsResponseItem)


/**
 * @summary Queue a submission for AI processing (runs in the background)
 */
export const postApiAdminSubmissionsIdProcessParams = zod.object({
  "id": zod.uuid()
})


/**
 * @summary The page text (Markdown) archived at submit time
 */
export const getApiAdminSubmissionsIdArchiveTextParams = zod.object({
  "id": zod.uuid()
})

export const getApiAdminSubmissionsIdArchiveTextQueryParams = zod.object({
  "download": zod.string().optional()
})


/**
 * @summary Save a manually edited archive text (e.g. a pasted paywalled article)
 */
export const putApiAdminSubmissionsIdArchiveTextParams = zod.object({
  "id": zod.uuid()
})

export const putApiAdminSubmissionsIdArchiveTextBodyTextMax = 200000;



export const putApiAdminSubmissionsIdArchiveTextBody = zod.object({
  "text": zod.string().min(1).max(putApiAdminSubmissionsIdArchiveTextBodyTextMax)
})

export const putApiAdminSubmissionsIdArchiveTextResponse = zod.object({
  "ok": zod.literal(true)
})


/**
 * @summary Reject a link out of the Ehdotusjono (also cancels an in-flight processing run)
 */
export const postApiAdminSubmissionsIdRejectParams = zod.object({
  "id": zod.uuid()
})

export const postApiAdminSubmissionsIdRejectResponse = zod.object({
  "ok": zod.literal(true)
})


/**
 * @summary The rejected-links archive, newest rejection first
 */
export const getApiAdminSubmissionsRejectedResponseItem = zod.object({
  "id": zod.uuid(),
  "url": zod.string(),
  "title": zod.string(),
  "description": zod.string(),
  "siteName": zod.string(),
  "createdAt": zod.iso.datetime({}),
  "archiveStatus": zod.union([zod.literal('pending'),zod.literal('ok'),zod.literal('paywalled'),zod.literal('failed'),zod.literal(null)]).nullable(),
  "hasArchivedText": zod.boolean(),
  "processing": zod.boolean(),
  "processError": zod.string().nullable()
}).and(zod.object({
  "rejectedAt": zod.iso.datetime({})
}))
export const getApiAdminSubmissionsRejectedResponse = zod.array(getApiAdminSubmissionsRejectedResponseItem)


/**
 * @summary Restore a rejected link back to the Ehdotusjono
 */
export const postApiAdminSubmissionsIdRestoreParams = zod.object({
  "id": zod.uuid()
})

export const postApiAdminSubmissionsIdRestoreResponse = zod.object({
  "id": zod.uuid(),
  "url": zod.string(),
  "title": zod.string(),
  "description": zod.string(),
  "siteName": zod.string(),
  "createdAt": zod.iso.datetime({}),
  "archiveStatus": zod.union([zod.literal('pending'),zod.literal('ok'),zod.literal('paywalled'),zod.literal('failed'),zod.literal(null)]).nullable(),
  "hasArchivedText": zod.boolean(),
  "processing": zod.boolean(),
  "processError": zod.string().nullable()
})
