/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Rahaaon API
 * Crowdsourced tracker of wasteful public spending (rahaaon.fi).
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';

/**
 * @summary Liveness probe
 */
export const getApiHealthResponse = zod.object({
  "status": zod.enum(['ok'])
})


/**
 * @summary Readiness probe (checks the database)
 */
export const getApiHealthReadyResponse = zod.object({
  "status": zod.enum(['ok', 'degraded']),
  "db": zod.enum(['up', 'down'])
})


/**
 * @summary Current editorial user, or null when not signed in
 */
export const getApiMeResponse = zod.union([zod.object({
  "user": zod.object({
  "id": zod.string(),
  "email": zod.string(),
  "name": zod.string()
})
}),zod.null()])


/**
 * @summary Published feed items (visible only), newest first
 */
export const getApiItemsResponseItem = zod.object({
  "id": zod.uuid(),
  "title": zod.string(),
  "amountEur": zod.number(),
  "entity": zod.string(),
  "category": zod.enum(['Rakentaminen', 'IT-hankkeet', 'Konsultit', 'Kulttuuri', 'Viestintä', 'Matkustus', 'Muu']),
  "sourceName": zod.string(),
  "sourceUrl": zod.string(),
  "summary": zod.string(),
  "quote": zod.string(),
  "hidden": zod.boolean(),
  "publishedAt": zod.iso.datetime({}),
  "votes": zod.number(),
  "voted": zod.boolean()
})
export const getApiItemsResponse = zod.array(getApiItemsResponseItem)


/**
 * @summary Toggle the visitor's "this is a waste" vote
 */
export const postApiItemsIdVoteParams = zod.object({
  "id": zod.uuid()
})

export const postApiItemsIdVoteResponse = zod.object({
  "votes": zod.number(),
  "voted": zod.boolean()
})


/**
 * @summary All published items including hidden ones (editorial)
 */
export const getApiAdminItemsResponseItem = zod.object({
  "id": zod.uuid(),
  "title": zod.string(),
  "amountEur": zod.number(),
  "entity": zod.string(),
  "category": zod.enum(['Rakentaminen', 'IT-hankkeet', 'Konsultit', 'Kulttuuri', 'Viestintä', 'Matkustus', 'Muu']),
  "sourceName": zod.string(),
  "sourceUrl": zod.string(),
  "summary": zod.string(),
  "quote": zod.string(),
  "hidden": zod.boolean(),
  "publishedAt": zod.iso.datetime({}),
  "votes": zod.number(),
  "voted": zod.boolean()
})
export const getApiAdminItemsResponse = zod.array(getApiAdminItemsResponseItem)


/**
 * @summary Hide an item from the feed, or restore it (editorial)
 */
export const patchApiAdminItemsIdParams = zod.object({
  "id": zod.uuid()
})

export const patchApiAdminItemsIdBody = zod.object({
  "hidden": zod.boolean()
})

export const patchApiAdminItemsIdResponse = zod.object({
  "ok": zod.literal(true)
})


/**
 * @summary Run the AI extraction for a link, without submitting anything
 */
export const postApiSuggestionsPreviewBodyUrlMax = 2000;



export const postApiSuggestionsPreviewBody = zod.object({
  "url": zod.url().max(postApiSuggestionsPreviewBodyUrlMax)
})

export const postApiSuggestionsPreviewResponseConfidenceMin = 0;
export const postApiSuggestionsPreviewResponseConfidenceMax = 100;



export const postApiSuggestionsPreviewResponse = zod.object({
  "title": zod.string(),
  "amountEur": zod.number(),
  "entity": zod.string(),
  "category": zod.enum(['Rakentaminen', 'IT-hankkeet', 'Konsultit', 'Kulttuuri', 'Viestintä', 'Matkustus', 'Muu']),
  "sourceName": zod.string(),
  "summary": zod.string(),
  "aiNote": zod.string(),
  "confidence": zod.number().min(postApiSuggestionsPreviewResponseConfidenceMin).max(postApiSuggestionsPreviewResponseConfidenceMax)
})


/**
 * @summary Submit a link to the editorial queue (anonymous)
 */
export const postApiSuggestionsBodyUrlMax = 2000;



export const postApiSuggestionsBody = zod.object({
  "url": zod.url().max(postApiSuggestionsBodyUrlMax)
})


/**
 * @summary The editorial queue: pending suggestions, newest first
 */
export const getApiAdminSuggestionsResponseItem = zod.object({
  "id": zod.uuid(),
  "url": zod.string(),
  "title": zod.string(),
  "amountEur": zod.number(),
  "entity": zod.string(),
  "category": zod.enum(['Rakentaminen', 'IT-hankkeet', 'Konsultit', 'Kulttuuri', 'Viestintä', 'Matkustus', 'Muu']),
  "sourceName": zod.string(),
  "summary": zod.string(),
  "aiNote": zod.string(),
  "confidence": zod.number(),
  "createdAt": zod.iso.datetime({})
})
export const getApiAdminSuggestionsResponse = zod.array(getApiAdminSuggestionsResponseItem)


/**
 * @summary Apply editorial edits to a pending suggestion
 */
export const patchApiAdminSuggestionsIdParams = zod.object({
  "id": zod.uuid()
})

export const patchApiAdminSuggestionsIdBodyTitleMax = 300;

export const patchApiAdminSuggestionsIdBodySummaryMax = 2000;

export const patchApiAdminSuggestionsIdBodyAmountEurMin = 0;

export const patchApiAdminSuggestionsIdBodyEntityMax = 120;



export const patchApiAdminSuggestionsIdBody = zod.object({
  "title": zod.string().min(1).max(patchApiAdminSuggestionsIdBodyTitleMax).optional(),
  "summary": zod.string().min(1).max(patchApiAdminSuggestionsIdBodySummaryMax).optional(),
  "amountEur": zod.number().min(patchApiAdminSuggestionsIdBodyAmountEurMin).optional(),
  "entity": zod.string().min(1).max(patchApiAdminSuggestionsIdBodyEntityMax).optional(),
  "category": zod.enum(['Rakentaminen', 'IT-hankkeet', 'Konsultit', 'Kulttuuri', 'Viestintä', 'Matkustus', 'Muu']).optional()
})

export const patchApiAdminSuggestionsIdResponse = zod.object({
  "id": zod.uuid(),
  "url": zod.string(),
  "title": zod.string(),
  "amountEur": zod.number(),
  "entity": zod.string(),
  "category": zod.enum(['Rakentaminen', 'IT-hankkeet', 'Konsultit', 'Kulttuuri', 'Viestintä', 'Matkustus', 'Muu']),
  "sourceName": zod.string(),
  "summary": zod.string(),
  "aiNote": zod.string(),
  "confidence": zod.number(),
  "createdAt": zod.iso.datetime({})
})


/**
 * @summary Publish a pending suggestion to the feed
 */
export const postApiAdminSuggestionsIdApproveParams = zod.object({
  "id": zod.uuid()
})

export const postApiAdminSuggestionsIdApproveResponse = zod.object({
  "itemId": zod.uuid()
})


/**
 * @summary Reject a pending suggestion
 */
export const postApiAdminSuggestionsIdRejectParams = zod.object({
  "id": zod.uuid()
})

export const postApiAdminSuggestionsIdRejectResponse = zod.object({
  "ok": zod.literal(true)
})
